#Code generated by CoPilot

import os
import tkinter as tk
from tkinter import filedialog
import pandas as pd

# Hide the Tkinter root window
root = tk.Tk()
root.withdraw()

# 1. Ask user to select a CSV file
csv_path = filedialog.askopenfilename(
    title="Select CSV File",
    filetypes=[("CSV Files", "*.csv")]
)

if not csv_path:
    print("No file selected.")
    exit()

# 2. Load CSV into a dataframe
# Assumes the first row contains column headers
df = pd.read_csv(csv_path)
print(df.head())

# 3. Ask user for a sigma value
sigma_input = input("Enter the sigma value to filter on: ")

# Attempt to convert to numeric if possible
try:
    sigma_input = float(sigma_input)
except ValueError:
    pass

# 4. Filter dataframe to rows with the specified sigma value
filtered_df = df[df["size_sigma"] == sigma_input]

# 5. Save filtered dataframe as a new CSV in the same directory
input_dir = os.path.dirname(csv_path)
input_file = os.path.splitext(os.path.basename(csv_path))[0]

output_path = os.path.join(
    input_dir,
    f"{input_file}_sigma_{sigma_input}.csv"
)

filtered_df.to_csv(output_path, index=False)

print(f"Filtered dataframe contains {len(filtered_df)} rows.")
print(f"Output saved to:\n{output_path}")